# Generated by Django 3.2.16 on 2023-07-11 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='total_rating',
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='acting',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='final',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='music',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='story',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='visual',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
