# Generated by Django 3.2.16 on 2023-07-11 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20230711_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(help_text='Maximum of 1000 symbols', max_length=1000, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='acting',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='acting'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='final',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='music',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='music'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='story',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='story'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='total_rating',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='total_rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='visual',
            field=models.PositiveSmallIntegerField(default=5, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='visual'),
        ),
    ]
