# Generated by Django 3.2.16 on 2023-07-11 18:57

import core.mixins
import django.core.validators
from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum of 50 symbols', max_length=50, verbose_name='name')),
                ('surname', models.CharField(help_text='Maximum of 50 symbols', max_length=50, verbose_name='surname')),
                ('height', models.PositiveSmallIntegerField(help_text='Min - 120, max - 250', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxLengthValidator(250)], verbose_name='height')),
                ('date_of_birth', models.DateTimeField(null=True, verbose_name='date_of_birth')),
                ('place_of_birth', models.CharField(help_text='Maximum of 200 symbols', max_length=200, null=True, verbose_name='place_of_birth')),
                ('image', models.ImageField(default='images/default_avatar.png', upload_to=persons.models.Person.get_image_path, verbose_name='image')),
                ('career', models.ManyToManyField(to='roles.Role')),
                ('genres', models.ManyToManyField(to='genres.Genre')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
            bases=(core.mixins.ImageMixin, models.Model),
        ),
    ]
