# Generated by Django 3.2.16 on 2023-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date_of_birth'),
        ),
    ]
