# Generated by Django 3.2.16 on 2023-07-13 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.PositiveSmallIntegerField(help_text='Min - 120, max - 250', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='height'),
        ),
    ]
