# Generated by Django 3.2.16 on 2023-08-02 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_person_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Min - 120, max - 250', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='Maximum of 200 symbols', max_length=200, null=True, verbose_name='place_of_birth'),
        ),
    ]
