# Generated by Django 3.2.16 on 2023-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Maximum of 500 symbols', max_length=500, null=True, verbose_name='bio'),
        ),
    ]
