from django.contrib.auth import views as auth_views
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='users/change_password.html'
        ),
        name='change_password',
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='users/change_password_done.html',
        ),
        name='change_password_done',
    ),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/reset_password.html',
        ),
        name='reset_password',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/reset_password_done.html',
        ),
        name='reset_password_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/reset_password_confirm.html',
        ),
        name='reset_password_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/reset_password_complete.html',
        ),
        name='reset_password_complete',
    ),
    path(
        'signup/',
        views.SignUpView.as_view(),
        name='signup',
    ),
    path(
        'signup/done/',
        views.SignUpDoneView.as_view(),
        name='signup_done',
    ),
    path(
        'activation/done/',
        views.AccountActivationDoneView.as_view(),
        name='activation_done',
    ),
    path(
        'activation/<str:username>/',
        views.AccountActivationView.as_view(),
        name='activation',
    ),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile',
    ),
    path(
        'list/',
        views.UserListView.as_view(),
        name='userlist',
    ),
    path(
        'list/search/',
        views.SearchView.as_view(),
        name='search',
    ),
]
