# Generated by Django 3.2.16 on 2023-07-09 11:41

import core.mixins
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum of 100 symbols', max_length=100, verbose_name='name')),
                ('formatted_name', models.CharField(editable=False, max_length=100, verbose_name='formatted_name')),
                ('description', models.TextField(help_text='Maximum of 1000 symbols', max_length=1000, verbose_name='description')),
                ('image', models.ImageField(default='images/default_movie_image.jpeg', null=True, upload_to=movies.models.Movie.get_image_path, verbose_name='image')),
                ('created_at', models.DateField(verbose_name='created_at')),
                ('uploaded_at', models.DateField(auto_now=True, verbose_name='uploaded_at')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
            bases=(models.Model, core.mixins.ImageMixin),
        ),
    ]
