# Generated by Django 3.2.16 on 2023-07-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('movies', '0003_auto_20230709_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='genres.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, verbose_name='uploaded_at'),
        ),
    ]
