# Generated by Django 3.2.16 on 2023-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('movies', '0004_auto_20230711_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='artist',
            field=models.ManyToManyField(related_name='artist', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(null=True, verbose_name='budget'),
        ),
        migrations.AddField(
            model_name='movie',
            name='composer',
            field=models.ManyToManyField(related_name='composer', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(help_text='Maximum of 50 symbols', max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='montage',
            field=models.ManyToManyField(related_name='montage', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='operator',
            field=models.ManyToManyField(related_name='operator', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(related_name='producer', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenwriter',
            field=models.ManyToManyField(related_name='screenwriter', to='persons.Person'),
        ),
    ]
