# Generated by Django 3.2.16 on 2023-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_date_of_birth'),
        ('movies', '0005_auto_20230711_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='persons.Person'),
        ),
    ]
