# Generated by Django 3.2.16 on 2023-08-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20230802_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='kinopoisk_link'),
        ),
    ]
